title: Jake Warmflash # your name (or website title) here
logo: "/images/Jake_image.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist, Statistician, Data Engineer <br>
  I'm a Data Science Master's Student, currently pursuing a degree from Willamette University. I want to use my analytical skills to work for a company which shares my ideals, fighting climate change or working directly to improve the lives of others. I'm interested in the ways we can use data to explore our world and find patterns to help us better understand the trends that explain our lives.
  I graduated from Lewis & Clark College in 2021 with a degree in Mathematics. After graduating, I worked as a semiconductor manufacturing technician for Intel, before starting my secondary education at Willamette.
  <a href="https://www.linkedin.com/in/jacobwarmflash/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
